FROM golang:1.26-alpine as builder

RUN apk add --update --no-cache ca-certificates tzdata git make bash && update-ca-certificates

ADD . /opt
WORKDIR /opt

RUN git update-index --refresh; make build

FROM alpine:3.23 as runner

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /opt/mcoa-gateway /bin/mcoa-gateway

ARG BUILD_DATE
ARG VERSION
ARG VCS_REF
ARG DOCKERFILE_PATH

USER 10000:10000

LABEL vendor="Stolostron" \
    name="stolostron/mcoa-gateway" \
    description="MCOA Gateway" \
    io.k8s.display-name="stolostron/mcoa-gateway" \
    io.k8s.description="MCOA Gateway" \
    maintainer="Stolostron <team-monitoring@redhat.com>" \
    version="$VERSION" \
    org.label-schema.build-date=$BUILD_DATE \
    org.label-schema.description="MCOA Gateway" \
    org.label-schema.docker.cmd="docker run --rm stolostron/mcoa-gateway" \
    org.label-schema.docker.dockerfile=$DOCKERFILE_PATH \
    org.label-schema.name="stolostron/mcoa-gateway" \
    org.label-schema.schema-version="1.0" \
    org.label-schema.vcs-branch=$VCS_BRANCH \
    org.label-schema.vcs-ref=$VCS_REF \
    org.label-schema.vcs-url="https://github.com/stolostron/mcoa-gateway" \
    org.label-schema.vendor="stolostron/mcoa-gateway" \
    org.label-schema.version=$VERSION


ENTRYPOINT ["/bin/mcoa-gateway"]
